enum CronMinutesMode { EVERY_MINUTE, EVERY_N_MINUTES, SELECTED_MINUTES }

enum CronHoursMode { EVERY_HOUR, EVERY_N_HOURS, SELECTED_HOURS }

enum CronDayOfMonthMode { EVERY_DAY, SELECTED_DAYS }

enum CronMonthMode { EVERY_MONTH, SELECTED_MONTHS }

enum CronDayOfWeekMode { EVERY_DAY_OF_WEEK, SELECTED_DAYS_OF_WEEK }
